### ISSUE TITLE
I want to install Priiloader on a vWii, but i am worried that i will brick my Wii U

### ISSUE THREAD

**Issue by Helpo-beep** [DacoTaco/priiloader#294] opened 2021-11-26 18:24 UTC
is there a way to install it without problems on wii u?

**Comment by TheTechRobo** [comment] 2021-11-26 18:56
Not as of now as the vWii System Menu is encrypted. Duplicate of #268.

**Comment by DacoTaco** [comment] 2021-11-26 19:07
basically, what @TheTechRobo said.
don't even try it with older versions, it will brick vWii

**Closed by DacoTaco** 2021-11-26 19:07 UTC
