### ISSUE TITLE
USB Loader HUD bugged

### ISSUE THREAD

**Issue by Djdog1208** [DacoTaco/priiloader#370] opened 2024-05-04 21:29 UTC
On USB loader GX when on the Grid Organization, the Channel screens for the game are corrupted furthermore, when opening a game, it doesn’t show the start and settings buttons as well. I’m running this Priiloader on the vWii so idk if this happens on Wii. If this could be fixed I would very much appreciate it.

**Comment by DacoTaco** [comment] 2024-05-04 21:30
duplicate of #365

**Closed by DacoTaco** 2024-05-04 21:30 UTC
